# Generated by Django 4.2.11 on 2024-03-13 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_age', models.IntegerField(db_column='MinAge')),
                ('max_age', models.IntegerField(db_column='MaxAge')),
                ('age_group', models.CharField(db_column='AgeGroup', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ConfirmationType',
            fields=[
                ('code', models.CharField(db_column='Code', max_length=3, primary_key=True, serialize=False)),
                ('confirmation_type', models.CharField(db_column='ConfirmationType', max_length=50)),
            ],
            options={
                'db_table': 'ConfirmationTypes',
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('code', models.CharField(db_column='Code', max_length=1, primary_key=True, serialize=False)),
                ('gender', models.CharField(db_column='Gender', max_length=50)),
            ],
            options={
                'db_table': 'Gender',
            },
        ),
        migrations.CreateModel(
            name='HealthFacility',
            fields=[
                ('id', models.IntegerField(db_column='HFID', primary_key=True, serialize=False)),
                ('code', models.CharField(db_column='HFCode', max_length=8)),
                ('name', models.CharField(db_column='HFName', max_length=100)),
                ('level', models.CharField(db_column='HFLevel', max_length=1)),
            ],
            options={
                'db_table': 'HealthFacilities',
            },
        ),
        migrations.CreateModel(
            name='ICD',
            fields=[
                ('id', models.IntegerField(db_column='ICDID', primary_key=True, serialize=False)),
                ('code', models.CharField(db_column='ICDCode', max_length=6)),
                ('name', models.CharField(db_column='ICDName', max_length=255)),
            ],
            options={
                'db_table': 'ICDCodes',
            },
        ),
        migrations.CreateModel(
            name='LegalForm',
            fields=[
                ('code', models.CharField(db_column='LegalFormCode', max_length=1, primary_key=True, serialize=False)),
                ('legal_form', models.CharField(db_column='LegalForms', max_length=50)),
            ],
            options={
                'db_table': 'LegalForms',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.IntegerField(db_column='LocationId', primary_key=True, serialize=False)),
                ('code', models.CharField(db_column='LocationCode', max_length=8)),
                ('name', models.CharField(db_column='LocationName', max_length=50)),
                ('male_population', models.IntegerField(db_column='MalePopulation')),
                ('female_population', models.IntegerField(db_column='FemalePopulation')),
                ('other_population', models.IntegerField(db_column='OtherPopulation')),
                ('households', models.IntegerField(db_column='Households')),
                ('parent_id', models.ForeignKey(db_column='ParentLocationId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='dashboard_etl.location')),
            ],
            options={
                'db_table': 'Locations',
            },
        ),
        migrations.CreateModel(
            name='PayerType',
            fields=[
                ('code', models.CharField(db_column='Code', max_length=1, primary_key=True, serialize=False)),
                ('payer_type', models.CharField(db_column='PayerType', max_length=50)),
            ],
            options={
                'db_table': 'PayerType',
            },
        ),
        migrations.CreateModel(
            name='VisitsByInsuree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visits', models.IntegerField(db_column='TotalVisit')),
                ('period', models.DateField(db_column='InsuredDate')),
                ('age', models.IntegerField(db_column='Age')),
                ('confirmation_type', models.ForeignKey(db_column='ConfirmationType', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='dashboard_etl.confirmationtype')),
                ('gender', models.ForeignKey(db_column='Gender', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='dashboard_etl.gender')),
                ('health_facility', models.ForeignKey(db_column='HFId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='dashboard_etl.healthfacility')),
                ('location', models.ForeignKey(db_column='LocationId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='dashboard_etl.location')),
            ],
            options={
                'db_table': 'VisitByInsurees',
            },
        ),
        migrations.CreateModel(
            name='PremiumCollected',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(db_column='Amount', decimal_places=2, max_digits=18)),
                ('pay_date', models.DateField(db_column='PayDate')),
                ('pay_type', models.CharField(db_column='PayType', max_length=1)),
                ('policy_stage', models.CharField(db_column='PolicyStage', max_length=1)),
                ('confirmation_type', models.ForeignKey(db_column='ConfirmationType', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='premiums', to='dashboard_etl.confirmationtype')),
                ('location', models.ForeignKey(db_column='LocationId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='premiums', to='dashboard_etl.location')),
                ('payer_type', models.ForeignKey(db_column='PayerTypeCode', max_length=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='premiums', to='dashboard_etl.payertype')),
            ],
            options={
                'db_table': 'PremiumCollected',
            },
        ),
        migrations.CreateModel(
            name='InsuredInsuree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insured_insurees', models.IntegerField(db_column='InsuredInsurees')),
                ('period', models.DateField(db_column='InsuredDate')),
                ('age', models.IntegerField(db_column='Age')),
                ('policy_stage', models.CharField(db_column='PolicyStage', max_length=1)),
                ('confirmation_type', models.ForeignKey(db_column='ConfirmationType', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insured_insurees', to='dashboard_etl.confirmationtype')),
                ('gender', models.ForeignKey(db_column='Gender', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insured_insurees', to='dashboard_etl.gender')),
                ('location', models.ForeignKey(db_column='LocationId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insured_insurees', to='dashboard_etl.location')),
            ],
            options={
                'db_table': 'InsuredInsurees',
            },
        ),
        migrations.CreateModel(
            name='InsuredHousehold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insured_households', models.IntegerField(db_column='InsuredHouseholds')),
                ('period', models.DateField(db_column='InsuredDate')),
                ('age', models.IntegerField(db_column='Age')),
                ('policy_stage', models.CharField(db_column='PolicyStage', max_length=1)),
                ('confirmation_type', models.ForeignKey(db_column='ConfirmationType', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insured_households', to='dashboard_etl.confirmationtype')),
                ('gender', models.ForeignKey(db_column='Gender', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insured_households', to='dashboard_etl.gender')),
                ('location', models.ForeignKey(db_column='LocationId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insured_households', to='dashboard_etl.location')),
            ],
            options={
                'db_table': 'InsuredHouseholds',
            },
        ),
        migrations.AddField(
            model_name='healthfacility',
            name='legal_form',
            field=models.ForeignKey(db_column='LegalForm', max_length=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='health_facilities', to='dashboard_etl.legalform'),
        ),
        migrations.AddField(
            model_name='healthfacility',
            name='location',
            field=models.ForeignKey(db_column='LocationId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='health_facilities', to='dashboard_etl.location'),
        ),
        migrations.CreateModel(
            name='ClaimReceived',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claims_received', models.IntegerField(db_column='ClaimReceived')),
                ('amount', models.DecimalField(db_column='Amount', decimal_places=2, max_digits=18)),
                ('approved', models.DecimalField(db_column='Approved', decimal_places=2, max_digits=18)),
                ('received_date', models.DateField(db_column='ReceivedDate')),
                ('age', models.IntegerField(db_column='Age')),
                ('care_type', models.CharField(db_column='CareType', max_length=4)),
                ('visit_type', models.CharField(db_column='VisitType', max_length=1)),
                ('processing_days', models.IntegerField(db_column='ProcessingDays')),
                ('claim_status', models.IntegerField(db_column='ClaimStatus')),
                ('review_status', models.IntegerField(db_column='ReviewStatus')),
                ('hf_days', models.IntegerField(db_column='DaysInHF')),
                ('confirmation_type', models.ForeignKey(db_column='ConfirmationType', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to='dashboard_etl.confirmationtype')),
                ('gender', models.ForeignKey(db_column='Gender', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to='dashboard_etl.gender')),
                ('health_facility', models.ForeignKey(db_column='HFId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to='dashboard_etl.healthfacility')),
                ('icd', models.ForeignKey(db_column='ICDID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to='dashboard_etl.icd')),
                ('location', models.ForeignKey(db_column='LocationId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to='dashboard_etl.location')),
            ],
            options={
                'db_table': 'ClaimReceived',
            },
        ),
        migrations.CreateModel(
            name='ActiveInsuree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_insurees', models.IntegerField(db_column='ActiveInsurees')),
                ('period', models.DateField(db_column='ActivePeriod')),
                ('age', models.IntegerField(db_column='Age')),
                ('confirmation_type', models.ForeignKey(db_column='ConfirmationType', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_insurees', to='dashboard_etl.confirmationtype')),
                ('gender', models.ForeignKey(db_column='Gender', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_insurees', to='dashboard_etl.gender')),
                ('location', models.ForeignKey(db_column='LocationId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_insurees', to='dashboard_etl.location')),
            ],
            options={
                'db_table': 'ActiveInsurees',
            },
        ),
        migrations.CreateModel(
            name='ActiveHousehold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_households', models.IntegerField(db_column='ActiveHouseholds')),
                ('period', models.DateField(db_column='ActivePeriod')),
                ('age', models.IntegerField(db_column='Age')),
                ('benefit_amount', models.DecimalField(db_column='BenefitAmount', decimal_places=2, max_digits=18)),
                ('confirmation_type', models.ForeignKey(db_column='ConfirmationType', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_households', to='dashboard_etl.confirmationtype')),
                ('gender', models.ForeignKey(db_column='Gender', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_households', to='dashboard_etl.gender')),
                ('location', models.ForeignKey(db_column='LocationId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_households', to='dashboard_etl.location')),
            ],
            options={
                'db_table': 'ActiveHouseholds',
            },
        ),
    ]
