# Generated by Django 4.2.11 on 2024-03-13 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_etl', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='agegroup',
            table='AgeGroup',
        ),
    ]
