# Generated by Django 4.2.11 on 2024-03-13 15:50

from django.db import migrations


class Migration(migrations.Migration):

    def seed_age_group(apps, schema_editor):

        from ..models import AgeGroup
        age_group_data = [
            {"min_age": 0, "max_age": 5, "age_group": "< 5"},
            {"min_age": 6, "max_age": 10, "age_group": "6 - 10"},
            {"min_age": 11, "max_age": 20, "age_group": "11 - 20"},
            {"min_age": 21, "max_age": 35, "age_group": "21 - 35"},
            {"min_age": 36, "max_age": 45, "age_group": "36 - 45"},
            {"min_age": 46, "max_age": 60, "age_group": "46 - 60"},
            {"min_age": 61, "max_age": 70, "age_group": "61 - 70"},
            {"min_age": 71, "max_age": 999, "age_group": "71+"}
        ]

        for group in age_group_data:
            AgeGroup.objects.using("dashboard_db").create(**group)



    dependencies = [
        ('dashboard_etl', '0002_alter_agegroup_table'),
    ]



    operations = [
        migrations.RunPython(
            seed_age_group
        ),
    ]
