# Generated by Django 4.2.11 on 2024-03-13 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_etl', '0003_seed_age_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='parent_id',
            new_name='parent',
        ),
    ]
