# Generated by Django 4.2.11 on 2024-03-13 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_etl', '0004_rename_parent_id_location_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='female_population',
            field=models.IntegerField(db_column='FemalePopulation', null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='households',
            field=models.IntegerField(db_column='Households', null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='male_population',
            field=models.IntegerField(db_column='MalePopulation', null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='other_population',
            field=models.IntegerField(db_column='OtherPopulation', null=True),
        ),
    ]
