# Generated by Django 4.2.11 on 2024-03-18 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_etl', '0005_alter_location_female_population_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activehousehold',
            name='last_id',
            field=models.IntegerField(db_column='LastId', default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='female_population',
            field=models.IntegerField(blank=True, db_column='FemalePopulation', null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='households',
            field=models.IntegerField(blank=True, db_column='Households', null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='male_population',
            field=models.IntegerField(blank=True, db_column='MalePopulation', null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='other_population',
            field=models.IntegerField(blank=True, db_column='OtherPopulation', null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='parent',
            field=models.ForeignKey(blank=True, db_column='ParentLocationId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='dashboard_etl.location'),
        ),
    ]
