# Generated by Django 4.2.11 on 2024-03-22 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_etl', '0006_activehousehold_last_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeinsuree',
            name='last_id',
            field=models.IntegerField(db_column='LastId', default=None),
            preserve_default=False,
        ),
    ]
