# Generated by Django 4.2.11 on 2024-03-25 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_etl', '0010_insuredhousehold_last_id_alter_insuredhousehold_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuredinsuree',
            name='last_id',
            field=models.IntegerField(db_column='LastId', default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='insuredinsuree',
            name='policy_stage',
            field=models.CharField(db_column='PolicyStage', max_length=1, null=True),
        ),
    ]
