# Generated by Django 4.2.11 on 2024-03-25 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_etl', '0011_insuredinsuree_last_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiumcollected',
            name='last_id',
            field=models.IntegerField(blank=True, db_column='LastId', null=True),
        ),
        migrations.AlterField(
            model_name='premiumcollected',
            name='amount',
            field=models.DecimalField(db_column='Amount', decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='premiumcollected',
            name='pay_type',
            field=models.CharField(db_column='PayType', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='premiumcollected',
            name='policy_stage',
            field=models.CharField(db_column='PolicyStage', max_length=1, null=True),
        ),
    ]
