# Generated by Django 4.2.11 on 2024-03-26 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_etl', '0012_premiumcollected_last_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitsbyinsuree',
            name='last_id',
            field=models.IntegerField(blank=True, db_column='LastId', null=True),
        ),
        migrations.AlterField(
            model_name='visitsbyinsuree',
            name='age',
            field=models.IntegerField(db_column='Age', null=True),
        ),
        migrations.AlterField(
            model_name='visitsbyinsuree',
            name='period',
            field=models.DateField(db_column='InsuredDate', null=True),
        ),
    ]
