# Generated by Django 4.2.11 on 2024-03-28 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_etl', '0014_alter_visitsbyinsuree_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activehousehold',
            name='active_households',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='activehousehold',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='activehousehold',
            name='benefit_amount',
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
        migrations.AlterField(
            model_name='activehousehold',
            name='confirmation_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_households', to='dashboard_etl.confirmationtype'),
        ),
        migrations.AlterField(
            model_name='activehousehold',
            name='gender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_households', to='dashboard_etl.gender'),
        ),
        migrations.AlterField(
            model_name='activehousehold',
            name='last_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='activehousehold',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_households', to='dashboard_etl.location'),
        ),
        migrations.AlterField(
            model_name='activehousehold',
            name='period',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='activeinsuree',
            name='active_insurees',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='activeinsuree',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='activeinsuree',
            name='confirmation_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_insurees', to='dashboard_etl.confirmationtype'),
        ),
        migrations.AlterField(
            model_name='activeinsuree',
            name='gender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_insurees', to='dashboard_etl.gender'),
        ),
        migrations.AlterField(
            model_name='activeinsuree',
            name='last_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='activeinsuree',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_insurees', to='dashboard_etl.location'),
        ),
        migrations.AlterField(
            model_name='activeinsuree',
            name='period',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='agegroup',
            name='age_group',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='agegroup',
            name='max_age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='agegroup',
            name='min_age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='claimreceived',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='claimreceived',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='claimreceived',
            name='approved',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='claimreceived',
            name='care_type',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='claimreceived',
            name='claim_status',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='claimreceived',
            name='claims_received',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='claimreceived',
            name='confirmation_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to='dashboard_etl.confirmationtype'),
        ),
        migrations.AlterField(
            model_name='claimreceived',
            name='gender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to='dashboard_etl.gender'),
        ),
        migrations.AlterField(
            model_name='claimreceived',
            name='health_facility',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to='dashboard_etl.healthfacility'),
        ),
        migrations.AlterField(
            model_name='claimreceived',
            name='hf_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='claimreceived',
            name='icd',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to='dashboard_etl.icd'),
        ),
        migrations.AlterField(
            model_name='claimreceived',
            name='last_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='claimreceived',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to='dashboard_etl.location'),
        ),
        migrations.AlterField(
            model_name='claimreceived',
            name='processing_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='claimreceived',
            name='received_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='claimreceived',
            name='review_status',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='claimreceived',
            name='visit_type',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='confirmationtype',
            name='code',
            field=models.CharField(max_length=3, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='confirmationtype',
            name='confirmation_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='gender',
            name='code',
            field=models.CharField(max_length=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='gender',
            name='gender',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='healthfacility',
            name='code',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='healthfacility',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='healthfacility',
            name='legal_form',
            field=models.ForeignKey(max_length=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='health_facilities', to='dashboard_etl.legalform'),
        ),
        migrations.AlterField(
            model_name='healthfacility',
            name='level',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='healthfacility',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='health_facilities', to='dashboard_etl.location'),
        ),
        migrations.AlterField(
            model_name='healthfacility',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='icd',
            name='code',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='icd',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='icd',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='insuredhousehold',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='insuredhousehold',
            name='confirmation_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insured_households', to='dashboard_etl.confirmationtype'),
        ),
        migrations.AlterField(
            model_name='insuredhousehold',
            name='gender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insured_households', to='dashboard_etl.gender'),
        ),
        migrations.AlterField(
            model_name='insuredhousehold',
            name='insured_households',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='insuredhousehold',
            name='last_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='insuredhousehold',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insured_households', to='dashboard_etl.location'),
        ),
        migrations.AlterField(
            model_name='insuredhousehold',
            name='period',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='insuredhousehold',
            name='policy_stage',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='insuredinsuree',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='insuredinsuree',
            name='confirmation_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insured_insurees', to='dashboard_etl.confirmationtype'),
        ),
        migrations.AlterField(
            model_name='insuredinsuree',
            name='gender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insured_insurees', to='dashboard_etl.gender'),
        ),
        migrations.AlterField(
            model_name='insuredinsuree',
            name='insured_insurees',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='insuredinsuree',
            name='last_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='insuredinsuree',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insured_insurees', to='dashboard_etl.location'),
        ),
        migrations.AlterField(
            model_name='insuredinsuree',
            name='period',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='insuredinsuree',
            name='policy_stage',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='legalform',
            name='code',
            field=models.CharField(max_length=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='legalform',
            name='legal_form',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='location',
            name='code',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='location',
            name='female_population',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='households',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='location',
            name='male_population',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='location',
            name='other_population',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='dashboard_etl.location'),
        ),
        migrations.AlterField(
            model_name='payertype',
            name='code',
            field=models.CharField(max_length=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='payertype',
            name='payer_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='premiumcollected',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='premiumcollected',
            name='confirmation_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='premiums', to='dashboard_etl.confirmationtype'),
        ),
        migrations.AlterField(
            model_name='premiumcollected',
            name='last_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='premiumcollected',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='premiums', to='dashboard_etl.location'),
        ),
        migrations.AlterField(
            model_name='premiumcollected',
            name='pay_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='premiumcollected',
            name='pay_type',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='premiumcollected',
            name='payer_type',
            field=models.ForeignKey(max_length=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='premiums', to='dashboard_etl.payertype'),
        ),
        migrations.AlterField(
            model_name='premiumcollected',
            name='policy_stage',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='visitsbyinsuree',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='visitsbyinsuree',
            name='confirmation_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='dashboard_etl.confirmationtype'),
        ),
        migrations.AlterField(
            model_name='visitsbyinsuree',
            name='gender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='dashboard_etl.gender'),
        ),
        migrations.AlterField(
            model_name='visitsbyinsuree',
            name='health_facility',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='dashboard_etl.healthfacility'),
        ),
        migrations.AlterField(
            model_name='visitsbyinsuree',
            name='last_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visitsbyinsuree',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='dashboard_etl.location'),
        ),
        migrations.AlterField(
            model_name='visitsbyinsuree',
            name='period',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='visitsbyinsuree',
            name='visits',
            field=models.IntegerField(),
        ),
        migrations.AlterModelTable(
            name='activehousehold',
            table=None,
        ),
        migrations.AlterModelTable(
            name='activeinsuree',
            table=None,
        ),
        migrations.AlterModelTable(
            name='agegroup',
            table=None,
        ),
        migrations.AlterModelTable(
            name='claimreceived',
            table=None,
        ),
        migrations.AlterModelTable(
            name='confirmationtype',
            table=None,
        ),
        migrations.AlterModelTable(
            name='gender',
            table=None,
        ),
        migrations.AlterModelTable(
            name='healthfacility',
            table=None,
        ),
        migrations.AlterModelTable(
            name='icd',
            table=None,
        ),
        migrations.AlterModelTable(
            name='insuredhousehold',
            table=None,
        ),
        migrations.AlterModelTable(
            name='insuredinsuree',
            table=None,
        ),
        migrations.AlterModelTable(
            name='legalform',
            table=None,
        ),
        migrations.AlterModelTable(
            name='location',
            table=None,
        ),
        migrations.AlterModelTable(
            name='payertype',
            table=None,
        ),
        migrations.AlterModelTable(
            name='premiumcollected',
            table=None,
        ),
        migrations.AlterModelTable(
            name='visitsbyinsuree',
            table=None,
        ),
    ]
