# Generated by Django 4.2.11 on 2024-03-28 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_etl', '0015_alter_activehousehold_active_households_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='activehousehold',
            table='active_households',
        ),
        migrations.AlterModelTable(
            name='activeinsuree',
            table='active_insurees',
        ),
        migrations.AlterModelTable(
            name='agegroup',
            table='age_groups',
        ),
        migrations.AlterModelTable(
            name='claimreceived',
            table='claims',
        ),
        migrations.AlterModelTable(
            name='confirmationtype',
            table='confirmation_types',
        ),
        migrations.AlterModelTable(
            name='gender',
            table='genders',
        ),
        migrations.AlterModelTable(
            name='healthfacility',
            table='health_facilities',
        ),
        migrations.AlterModelTable(
            name='icd',
            table='icd',
        ),
        migrations.AlterModelTable(
            name='insuredhousehold',
            table='insured_households',
        ),
        migrations.AlterModelTable(
            name='insuredinsuree',
            table='insured_insurees',
        ),
        migrations.AlterModelTable(
            name='legalform',
            table='legal_forms',
        ),
        migrations.AlterModelTable(
            name='location',
            table='locations',
        ),
        migrations.AlterModelTable(
            name='payertype',
            table='payer_types',
        ),
        migrations.AlterModelTable(
            name='premiumcollected',
            table='premiums',
        ),
        migrations.AlterModelTable(
            name='visitsbyinsuree',
            table='visits',
        ),
    ]
