# Generated by Django 4.2.11 on 2024-03-28 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_etl', '0016_alter_activehousehold_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activehousehold',
            name='confirmation_type',
            field=models.ForeignKey(db_column='confirmation_type', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_households', to='dashboard_etl.confirmationtype'),
        ),
        migrations.AlterField(
            model_name='activehousehold',
            name='gender',
            field=models.ForeignKey(db_column='gender', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_households', to='dashboard_etl.gender'),
        ),
        migrations.AlterField(
            model_name='activeinsuree',
            name='confirmation_type',
            field=models.ForeignKey(db_column='confirmation_type', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_insurees', to='dashboard_etl.confirmationtype'),
        ),
        migrations.AlterField(
            model_name='activeinsuree',
            name='gender',
            field=models.ForeignKey(db_column='gender', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_insurees', to='dashboard_etl.gender'),
        ),
        migrations.AlterField(
            model_name='claimreceived',
            name='confirmation_type',
            field=models.ForeignKey(db_column='confirmation_type', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to='dashboard_etl.confirmationtype'),
        ),
        migrations.AlterField(
            model_name='claimreceived',
            name='gender',
            field=models.ForeignKey(db_column='gender', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to='dashboard_etl.gender'),
        ),
        migrations.AlterField(
            model_name='healthfacility',
            name='legal_form',
            field=models.ForeignKey(db_column='legal_form', max_length=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='health_facilities', to='dashboard_etl.legalform'),
        ),
        migrations.AlterField(
            model_name='insuredhousehold',
            name='confirmation_type',
            field=models.ForeignKey(db_column='confirmation_type', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insured_households', to='dashboard_etl.confirmationtype'),
        ),
        migrations.AlterField(
            model_name='insuredhousehold',
            name='gender',
            field=models.ForeignKey(db_column='gender', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insured_households', to='dashboard_etl.gender'),
        ),
        migrations.AlterField(
            model_name='insuredinsuree',
            name='confirmation_type',
            field=models.ForeignKey(db_column='confirmation_type', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insured_insurees', to='dashboard_etl.confirmationtype'),
        ),
        migrations.AlterField(
            model_name='insuredinsuree',
            name='gender',
            field=models.ForeignKey(db_column='gender', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insured_insurees', to='dashboard_etl.gender'),
        ),
        migrations.AlterField(
            model_name='premiumcollected',
            name='confirmation_type',
            field=models.ForeignKey(db_column='confirmation_type', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='premiums', to='dashboard_etl.confirmationtype'),
        ),
        migrations.AlterField(
            model_name='premiumcollected',
            name='payer_type',
            field=models.ForeignKey(db_column='payer_type', max_length=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='premiums', to='dashboard_etl.payertype'),
        ),
        migrations.AlterField(
            model_name='visitsbyinsuree',
            name='confirmation_type',
            field=models.ForeignKey(db_column='confirmation_type', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='dashboard_etl.confirmationtype'),
        ),
        migrations.AlterField(
            model_name='visitsbyinsuree',
            name='gender',
            field=models.ForeignKey(db_column='gender', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='dashboard_etl.gender'),
        ),
    ]
